### ISSUE TITLE
Save button does nothing

### ISSUE THREAD

**Issue by erik-121** [tonytan4ever/Bootstrap-Form-Builder-V3V4#20]
Hi there,
Why the Save Current Form Layout does nothing?? Is there something I have to do?
Thanks :)

**Comment by tonytan4ever** [comment]
It is supposed to automatically download a form layout file for you:

![image](https://user-images.githubusercontent.com/1202903/43461536-bfe196c0-94a1-11e8-9740-69a57eb0e87a.png)

And then you can load this form layout file and your form will be reloaded.

Can you take a screenshot showing me what went wrong?

**Comment by erik-121** [comment]
I am afraid that It depends on the web browser, I am using Firefox (updated) and does nothing. It seems only works on Chrome, I've tried it.
The load form button works as supposed to do it.

One more question what about the code of the V4 Bootsrap? How can I use it? Thanks a lot

**Comment by tonytan4ever** [comment]
Thanks @erik-121,  this is indeed a bug.

I have fixed it and pushed it to both V4 and V3. 

Yes,  you can use V4 Bootstrap with it from [here](http://formbuilder-v4.tdjangoy.webfactional.com/).

**Comment by erik-121** [comment]
Thanks a lot to you.
Well I can use it from there, but where is the code if I want to use V4 Bootstrap?

:) nice one!

**Comment by tonytan4ever** [comment]
The V4 one is on V4 branch.

**Comment by erik-121** [comment]
Sorry I didn't see it. Thank you! :)
