### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by lorvent** [tonytan4ever/Bootstrap-Form-Builder-V3V4#23]
Hello,
can you please submit it to npm registry?

which brings more exposure.

Also, can you make v4 as master branch as bootstrap v4 is latest version

**Comment by lorvent** [comment]
PS: its better if you can include require.js file locally instead of referencing remote file.

**Comment by tonytan4ever** [comment]
I always try to keep up with upstream package version,  thus I alway require them from remote.
Currently I have no plan adding it to npm.
