### ISSUE TITLE
radio value changable

### ISSUE THREAD

**Issue by l0o0** [tonytan4ever/Bootstrap-Form-Builder-V3V4#9]
Hi, I am trying to find some way to make the radio value changable. Like the example below.
![default](https://user-images.githubusercontent.com/2743744/29446009-85c5e612-841c-11e7-80bb-32ecb4bd9ba9.png)  
The last radio is changable for some other unpredictable value.  I found a example from the Internet,  
![default](https://user-images.githubusercontent.com/2743744/29446339-4ee0a6f8-841e-11e7-8d43-132c55d489cc.png)
Is it possible to do this in our form builder?

**Comment by tonytan4ever** [comment]
I will be working on this new form control (snippet in the next week).
I don't think it's hard to add.

**Comment by l0o0** [comment]
Thank you for your help.

**Comment by tonytan4ever** [comment]
Hi,  after I looked close in what the current app does, there is a way to do what you want:

![modify_inline_widget_specificd](https://user-images.githubusercontent.com/1202903/30219225-664a850e-9489-11e7-8c0c-af8548c6c003.png)

Once you dropped an inline radio-button widget into the form,  click it, and you will be able to edit
all the details of this inline radio-button widget. 
To modify the label of each button,  modify the content **Radios**. Each button corresponds to each line in it.  You can modify the value of each button in **Radios Values** as well.  See my attachment above.

Notice the layout of the widget will be changed a little as you add more text to button labels,  that could be a bug, and we could fix that in the future.
